//                   NAVIGATION IN DOM


//              GETTING Element BY USING ID 


// let container = document.getElementById('sahil');
// console.log(container);



// let navbar = document.getElementById('nav');
// console.log(navbar);



//    GETTING Element BY USING CLASS


// let container2 = document.getElementsByClassName('container');
// console.log(container2);
// console.log(container2[0]);
// console.log(container2[1]);
// console.log(container2[2]);





//        GETTING Element BY USING SELECTORS



// let s1 = document.querySelector('.container')
// console.log("selector is "+ s1)


// let s2 = document.querySelector('#nav')
// console.log("selector is "+ s2)


// let s3 = document.querySelector('#para')
// console.log("selector is "+ s3)





//     GETTING Element BY USING SELECTOR ALL



// let selector = document.querySelectorAll('#nav');
// console.log("selector returns " , selector);
