//                                SETTIMEOUT  and CLEARTIMEOUT   EXAMPLES


// // 1.



// function abhishek(){
//     console.log("hello good morning ")
// }
// setTimeout (abhishek,5000);




// // 2.




// function a(name){
//     console.log("good morning "+name +" sir.")
// }

// timeout = setTimeout(a,5000,"ABHISHEK NAYAK");
// console.log(timeout)




// // 3.



// function sahil(name,favbook,favbrand,favhero,wife){
//     console.log("Hi Sir GoodMorning","\n",name + " When You Joined Our Website ");
//     prompt("Enter the Date:");
//     alert("You are Now Signing In To Our Website Sir");
//     console.log("your fav book is " + favbook);
//     console.log("your fav brand is " + favbrand);
//     console.log("your fav hero is " + favhero);
//     console.log("your  wife is " + wife);
// }

// let USERDATA = setTimeout(sahil,5000,"Abhishek Nayak","Think and Grow Rich","Peter England","Amitabh Bachan","Kshitun Nayak");
// console.log(USERDATA);


// // clearTimeout(USERDATA);











//                               SETINTERVAL AND CLEARINTERVAL



// // 4




// function sum(a,b,c){
//     console.log(a+b+c);
// }

// interval = setInterval(sum,5000,23,2,2);
// console.log(interval);
    




// // 5





// function sahil(name,favbook,favbrand,favhero,wife){
//     console.log("Hi Sir GoodMorning","\n",name + " When You Joined Our Website ");
//     prompt("Enter the Date:");
//     alert("You are Now Signing In To Our Website Sir");
//     console.log("your fav book is " + favbook);
//     console.log("your fav brand is " + favbrand);
//     console.log("your fav hero is " + favhero);
//     console.log("your  wife is " + wife);
// }

// let USERDATA = setInterval(sahil,5000,"Abhishek Nayak","Think and Grow Rich","Peter England","Amitabh Bachan","Kshitun Nayak");
// console.log(USERDATA);



// // clearInterval(USERDATA);


